### PR TITLE
maintenance and package correction

### PR DESCRIPTION
**Pull request by TacoTheDank**
- java 1.8 compatibility
- delete .idea from repo
- target pie
- update dependencies
- added imports to java files that were erroring
- declared several java files public to fix said errors (the ones in "Core", mostly)
- reformat code
- update gradle to 4.10.2

### CODE REVIEW

**Comment by Swarthon** [comment]
Thank you very much for the time you spent for that !

**Comment by TacoTheDank** [comment]
:P are you going to move StarkeVerben to gitlab at some point? your profile description hints that

**Comment by 24PaH** [comment]
As for StarkeVerben, we think about keeping the repo on GitHub and wait and see. The main reason is that the repo address is already connected to several things such as F-Droid, and it is simpler for us to leave it here.

**Comment by TacoTheDank** [comment]
Alright. Taking a vacation to Europe in a couple of months and it includes Germany, and I'd like to learn some stuff before I go haha

**Comment by Swarthon** [comment]
Deutsch is super leicht !

**Comment by 24PaH** [comment]
Viel Spaß!

**Pull request merged**
